import type { Assessment, ColumnDef } from './types'

export const COLUMNS: ColumnDef[] = [
  { id: 'd', title: 'D', subtitle: 'Бобрик Д.В. · ЗИт-3в' },
  { id: 'm', title: 'M', subtitle: 'примерно · лист ещё нет' },
  { id: 'shared', title: 'Общие', subtitle: 'скорее сдавать вместе' },
  { id: 'done', title: 'Done', subtitle: 'закрыто' },
]

/** Реальная разница D + похожие предметы M (его лист пока неизвестен) */
export const SEED: Assessment[] = [
  // —— общие (типичное пересечение IT / ВГТУ) ——
  {
    id: 's1',
    subject: 'Английский язык в профессиональной деятельности',
    short: 'ENG',
    professor: '',
    type: 'credit',
    owners: ['D', 'M'],
    column: 'shared',
  },
  {
    id: 's2',
    subject: 'Линейная алгебра и аналитическая геометрия',
    short: 'ЛААГ',
    professor: '',
    type: 'exam',
    owners: ['D', 'M'],
    column: 'shared',
  },
  {
    id: 's3',
    subject: 'Математический анализ',
    short: 'МАТАН',
    professor: '',
    type: 'exam',
    owners: ['D', 'M'],
    column: 'shared',
  },
  {
    id: 's4',
    subject: 'Объектно-ориентированное проектирование и программирование',
    short: 'ООП',
    professor: '',
    type: 'course_project',
    owners: ['D', 'M'],
    column: 'shared',
  },
  {
    id: 's5',
    subject: 'Основы алгоритмизации и программирования',
    short: 'ОАП',
    professor: '',
    type: 'coursework',
    owners: ['D', 'M'],
    column: 'shared',
  },
  {
    id: 's6',
    subject: 'Дискретная математика',
    short: 'ДМ',
    professor: '',
    type: 'credit',
    owners: ['D', 'M'],
    column: 'shared',
    note: 'у D — заяв',
  },
  {
    id: 's7',
    subject: 'Операционные системы',
    short: 'ОС',
    professor: '',
    type: 'exam',
    owners: ['D', 'M'],
    column: 'shared',
    note: 'у D — заяв',
  },
  {
    id: 's8',
    subject: 'Скриптовые языки программирования',
    short: 'СКР',
    professor: '',
    type: 'exam',
    owners: ['D', 'M'],
    column: 'shared',
  },

  // —— только D (из листа учёта) ——
  {
    id: 'd2',
    subject: 'Инструменты поддержки промышленной разработки программного обеспечения',
    short: 'ИППР',
    professor: '',
    type: 'credit',
    owners: ['D'],
    column: 'd',
  },
  {
    id: 'd3',
    subject: 'История белорусской государственности',
    short: 'ИБГ',
    professor: '',
    type: 'exam',
    owners: ['D'],
    column: 'd',
  },
  {
    id: 'd4',
    subject: 'История науки и техники',
    short: 'ИНТ',
    professor: '',
    type: 'diff_credit',
    owners: ['D'],
    column: 'd',
  },
  {
    id: 'd5',
    subject: 'Культурология',
    short: 'КУЛЬТ',
    professor: '',
    type: 'diff_credit',
    owners: ['D'],
    column: 'd',
  },
  {
    id: 'd9',
    subject: 'Ознакомительная практика',
    short: 'ПРАК',
    professor: '',
    type: 'practice',
    owners: ['D'],
    column: 'd',
    note: 'дифф.зачёт (практика)',
  },
  {
    id: 'd11',
    subject: 'Разработка пользовательского интерфейса приложений',
    short: 'UI',
    professor: '',
    type: 'credit',
    owners: ['D'],
    column: 'd',
  },
  {
    id: 'd12',
    subject: 'Системы компьютерной графики',
    short: 'СКГ',
    professor: '',
    type: 'credit',
    owners: ['D'],
    column: 'd',
  },
  {
    id: 'd14',
    subject: 'Специальные математические методы и функции',
    short: 'СММФ',
    professor: '',
    type: 'credit',
    owners: ['D'],
    column: 'd',
  },
  {
    id: 'd15',
    subject: 'Управление IT-проектами',
    short: 'ITPM',
    professor: '',
    type: 'credit',
    owners: ['D'],
    column: 'd',
  },
  {
    id: 'd16',
    subject: 'Электронные приборы',
    short: 'ЭП',
    professor: '',
    type: 'exam',
    owners: ['D'],
    column: 'd',
  },
  {
    id: 'd17',
    subject: 'Архитектура вычислительных систем',
    short: 'АВС',
    professor: '',
    type: 'credit',
    owners: ['D'],
    column: 'd',
    note: 'заяв',
  },
  {
    id: 'd18',
    subject: 'Белорусский язык (профессиональная лексика)',
    short: 'БЕЛ',
    professor: '',
    type: 'credit',
    owners: ['D'],
    column: 'd',
    note: 'заяв',
  },
  {
    id: 'd19',
    subject: 'Введение в разработку программного обеспечения',
    short: 'ВРПО',
    professor: '',
    type: 'credit',
    owners: ['D'],
    column: 'd',
    note: 'заяв',
  },
  {
    id: 'd21',
    subject: 'Математическое программирование',
    short: 'МП',
    professor: '',
    type: 'exam',
    owners: ['D'],
    column: 'd',
    note: 'заяв',
  },
  {
    id: 'd22',
    subject: 'Объектно-ориентированное проектирование и программирование',
    short: 'ООПэ',
    professor: '',
    type: 'exam',
    owners: ['D'],
    column: 'd',
    note: 'заяв · экзамен (отдельно от курс.пр.)',
  },
  {
    id: 'd24',
    subject: 'Современная политэкономия',
    short: 'СПЭ',
    professor: '',
    type: 'exam',
    owners: ['D'],
    column: 'd',
    note: 'заяв',
  },

  // —— только M (черновик, пока нет его листа) ——
  {
    id: 'm1',
    subject: 'Базы данных',
    short: 'БД',
    professor: '',
    type: 'exam',
    owners: ['M'],
    column: 'm',
    note: 'черновик M',
  },
  {
    id: 'm2',
    subject: 'Компьютерные сети',
    short: 'КС',
    professor: '',
    type: 'exam',
    owners: ['M'],
    column: 'm',
    note: 'черновик M',
  },
  {
    id: 'm3',
    subject: 'Философия',
    short: 'ФИЛ',
    professor: '',
    type: 'diff_credit',
    owners: ['M'],
    column: 'm',
    note: 'черновик M',
  },
  {
    id: 'm4',
    subject: 'Теория вероятностей и математическая статистика',
    short: 'ТВМС',
    professor: '',
    type: 'exam',
    owners: ['M'],
    column: 'm',
    note: 'черновик M',
  },
  {
    id: 'm5',
    subject: 'Веб-технологии',
    short: 'WEB',
    professor: '',
    type: 'credit',
    owners: ['M'],
    column: 'm',
    note: 'черновик M',
  },
  {
    id: 'm6',
    subject: 'Защита информации',
    short: 'ЗИ',
    professor: '',
    type: 'credit',
    owners: ['M'],
    column: 'm',
    note: 'черновик M',
  },
  {
    id: 'm7',
    subject: 'Экономика',
    short: 'ЭКОН',
    professor: '',
    type: 'exam',
    owners: ['M'],
    column: 'm',
    note: 'черновик M',
  },
]
