import type { Assessment, ColumnDef } from './types'

export const COLUMNS: ColumnDef[] = [
  { id: 'd', title: 'D', subtitle: 'Бобрик Д.В. · ЗИт-3в' },
  { id: 'm', title: 'M', subtitle: 'Лысиков М.Г. · ЗИт-4в' },
  { id: 'done', title: 'Done', subtitle: 'закрыто' },
]

/** Реальная разница D + лист M (преподы M пока неизвестны) */
export const SEED: Assessment[] = [
  // —— D (в т.ч. пересечения с M — отдельные карточки ниже) ——
  {
    id: 's1',
    subject: 'Английский язык в профессиональной деятельности',
    short: 'ENG',
    professor: 'Смирнова Елена Петровна',
    type: 'credit',
    owners: ['D'],
    column: 'd',
  },
  {
    id: 's2',
    subject: 'Линейная алгебра и аналитическая геометрия',
    short: 'ЛААГ',
    professor: 'Ковалёв Андрей Сергеевич',
    type: 'exam',
    owners: ['D'],
    column: 'd',
  },
  {
    id: 's3',
    subject: 'Математический анализ',
    short: 'МАТАН',
    professor: 'Петрова Наталья Ивановна',
    type: 'exam',
    owners: ['D'],
    column: 'd',
  },
  {
    id: 's4',
    subject: 'Объектно-ориентированное проектирование и программирование',
    short: 'ООП',
    professor: 'Васильева Ольга Дмитриевна',
    type: 'course_project',
    owners: ['D'],
    column: 'd',
  },
  {
    id: 's5',
    subject: 'Основы алгоритмизации и программирования',
    short: 'ОАП',
    professor: 'Морозов Иван Алексеевич',
    type: 'coursework',
    owners: ['D'],
    column: 'd',
  },
  {
    id: 's6',
    subject: 'Дискретная математика',
    short: 'ДМ',
    professor: 'Ковалёв Андрей Сергеевич',
    type: 'credit',
    owners: ['D'],
    column: 'd',
    notes: { D: 'заяв' },
  },
  {
    id: 's7',
    subject: 'Операционные системы',
    short: 'ОС',
    professor: 'Новиков Павел Викторович',
    type: 'exam',
    owners: ['D'],
    column: 'd',
    notes: { D: 'заяв' },
  },
  {
    id: 's8',
    subject: 'Скриптовые языки программирования',
    short: 'СКР',
    professor: 'Морозов Иван Алексеевич',
    type: 'exam',
    owners: ['D'],
    column: 'd',
  },

  // —— только D ——
  {
    id: 'd2',
    subject: 'Инструменты поддержки промышленной разработки программного обеспечения',
    short: 'ИППР',
    professor: 'Жукова Татьяна Михайловна',
    type: 'credit',
    owners: ['D'],
    column: 'd',
  },
  {
    id: 'd3',
    subject: 'История белорусской государственности',
    short: 'ИБГ',
    professor: 'Савченко Ирина Владимировна',
    type: 'exam',
    owners: ['D'],
    column: 'd',
  },
  {
    id: 'd4',
    subject: 'История науки и техники',
    short: 'ИНТ',
    professor: 'Савченко Ирина Владимировна',
    type: 'diff_credit',
    owners: ['D'],
    column: 'd',
  },
  {
    id: 'd5',
    subject: 'Культурология',
    short: 'КУЛЬТ',
    professor: 'Лебедева Мария Александровна',
    type: 'diff_credit',
    owners: ['D'],
    column: 'd',
  },
  {
    id: 'd9',
    subject: 'Ознакомительная практика',
    short: 'ПРАК',
    professor: 'Григорьев Сергей Николаевич',
    type: 'practice',
    owners: ['D'],
    column: 'd',
    notes: { D: 'дифф.зачёт (практика)' },
  },
  {
    id: 'd11',
    subject: 'Разработка пользовательского интерфейса приложений',
    short: 'UI',
    professor: 'Васильева Ольга Дмитриевна',
    type: 'credit',
    owners: ['D'],
    column: 'd',
  },
  {
    id: 'd12',
    subject: 'Системы компьютерной графики',
    short: 'СКГ',
    professor: 'Фёдоров Дмитрий Олегович',
    type: 'credit',
    owners: ['D'],
    column: 'd',
  },
  {
    id: 'd14',
    subject: 'Специальные математические методы и функции',
    short: 'СММФ',
    professor: 'Петрова Наталья Ивановна',
    type: 'credit',
    owners: ['D'],
    column: 'd',
  },
  {
    id: 'd15',
    subject: 'Управление IT-проектами',
    short: 'ITPM',
    professor: 'Жукова Татьяна Михайловна',
    type: 'credit',
    owners: ['D'],
    column: 'd',
  },
  {
    id: 'd16',
    subject: 'Электронные приборы',
    short: 'ЭП',
    professor: 'Орлов Алексей Игоревич',
    type: 'exam',
    owners: ['D'],
    column: 'd',
  },
  {
    id: 'd17',
    subject: 'Архитектура вычислительных систем',
    short: 'АВС',
    professor: 'Новиков Павел Викторович',
    type: 'credit',
    owners: ['D'],
    column: 'd',
    notes: { D: 'заяв' },
  },
  {
    id: 'd18',
    subject: 'Белорусский язык (профессиональная лексика)',
    short: 'БЕЛ',
    professor: 'Кузьмина Анна Романовна',
    type: 'credit',
    owners: ['D'],
    column: 'd',
    notes: { D: 'заяв' },
  },
  {
    id: 'd19',
    subject: 'Введение в разработку программного обеспечения',
    short: 'ВРПО',
    professor: 'Морозов Иван Алексеевич',
    type: 'credit',
    owners: ['D'],
    column: 'd',
    notes: { D: 'заяв' },
  },
  {
    id: 'd21',
    subject: 'Математическое программирование',
    short: 'МП',
    professor: 'Ковалёв Андрей Сергеевич',
    type: 'exam',
    owners: ['D'],
    column: 'd',
    notes: { D: 'заяв' },
  },
  {
    id: 'd22',
    subject: 'Объектно-ориентированное проектирование и программирование',
    short: 'ООПэ',
    professor: 'Васильева Ольга Дмитриевна',
    type: 'exam',
    owners: ['D'],
    column: 'd',
    notes: { D: 'заяв · экзамен (отдельно от курс.пр.)' },
  },
  {
    id: 'd24',
    subject: 'Современная политэкономия',
    short: 'СПЭ',
    professor: 'Волкова Екатерина Юрьевна',
    type: 'exam',
    owners: ['D'],
    column: 'd',
    notes: { D: 'заяв' },
  },

  // —— M · лист учёта разницы ЗИт-4в (преподы неизвестны) ——
  {
    id: 'm1',
    subject: 'История белорусской государственности',
    short: 'ИБГ',
    professor: '',
    type: 'exam',
    owners: ['M'],
    column: 'm',
  },
  {
    id: 'm2',
    subject: 'Современная политэкономия',
    short: 'СПЭ',
    professor: '',
    type: 'exam',
    owners: ['M'],
    column: 'm',
  },
  {
    id: 'm3',
    subject: 'Линейная алгебра и аналитическая геометрия',
    short: 'ЛААГ',
    professor: '',
    type: 'exam',
    owners: ['M'],
    column: 'm',
    notes: { M: 'заяв' },
  },
  {
    id: 'm4',
    subject: 'Математический анализ',
    short: 'МАТАН',
    professor: '',
    type: 'exam',
    owners: ['M'],
    column: 'm',
    notes: { M: 'заяв' },
  },
  {
    id: 'm5',
    subject: 'Теория вероятностей и математическая статистика',
    short: 'ТВМС',
    professor: '',
    type: 'credit',
    owners: ['M'],
    column: 'm',
    notes: { M: 'заяв' },
  },
  {
    id: 'm6',
    subject: 'Социальная психология / Культурология',
    short: 'СП/КУЛЬТ',
    professor: '',
    type: 'diff_credit',
    owners: ['M'],
    column: 'm',
  },
  {
    id: 'm7',
    subject: 'История науки и техники',
    short: 'ИНТ',
    professor: '',
    type: 'diff_credit',
    owners: ['M'],
    column: 'm',
  },
  {
    id: 'm8',
    subject: 'Английский язык в профессиональной деятельности',
    short: 'ENG',
    professor: '',
    type: 'credit',
    owners: ['M'],
    column: 'm',
  },
]
